# Combining & Merging Datasets in Pandas

In [54]:
import pandas as pd
import numpy as np

In [55]:
d1=pd.DataFrame(
    {"key":["a","b","c","d","e"],
     "num1":range(5)})


d2=pd.DataFrame(
    {"key":["b","c","e","f"],
     "num2":range(4)})

In [56]:
print(d1)
print('-'*20)
print(d2)

  key  num1
0   a     0
1   b     1
2   c     2
3   d     3
4   e     4
--------------------
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3


## Joining DataFrame

In [6]:
d1=pd.DataFrame(
    {"key":["a","b","c","d","e"],
     "num1":range(5)})


d2=pd.DataFrame(
    {"key":["b","c","e","f"],
     "num2":range(4)})

In [7]:
print(d1)
print('-'*20)
print(d2)

  key  num1
0   a     0
1   b     1
2   c     2
3   d     3
4   e     4
--------------------
  key  num2
0   b     0
1   c     1
2   e     2
3   f     3


In [8]:
pd.merge(d1, d2, on='key')

key  num1  num2
0   b     1     0
1   c     2     1
2   e     4     2

In [9]:
d3=pd.DataFrame(
    {"key1":["a","b","c","d","e"],
     "num1":range(5)})
d4=pd.DataFrame(
    {"key2":["b","c","e","f"],
     "num1":range(4)})

In [10]:
d3.head()

key1  num1
0    a     0
1    b     1
2    c     2
3    d     3
4    e     4

In [11]:
d4.head()

key2  num1
0    b     0
1    c     1
2    e     2
3    f     3

In [12]:
pd.merge(d3,d4,left_on="key1",right_on="key2", how = 'left')

key1  num1_x key2  num1_y
0    a       0  NaN     NaN
1    b       1    b     0.0
2    c       2    c     1.0
3    d       3  NaN     NaN
4    e       4    e     2.0

In [ ]:
pd.merge(d1,d2,on ='key',how="outer")

In [ ]:
pd.merge(d1,d2,on ='key',how="left")

In [ ]:
pd.merge(d1,d2,on ='key',how="right")

In [ ]:
pd.merge(d1,d2,on ='key',how='inner')

In [13]:
df1=pd.DataFrame(
    {"key":["a","b","c","c","d","e"],
     "num1":range(6),
     "count":["one","three","two",
              "one","one","two"]})
df2=pd.DataFrame(
    {"key":["b","c","e","f"],
     "num2":range(4),
     "count":["one","two","two","two"]})

In [14]:
df1.head()

key  num1  count
0   a     0    one
1   b     1  three
2   c     2    two
3   c     3    one
4   d     4    one

In [15]:
df2.head()

key  num2 count
0   b     0   one
1   c     1   two
2   e     2   two
3   f     3   two

In [16]:
pd.merge(df1,df2,left_on = ['key','count'],
         right_on = ['key','count'])

# on - ?????
# on = ['key', 'count']

key  num1 count  num2
0   c     2   two     1
1   e     5   two     2

In [17]:
pd.merge(df1, df2, on=['key', 'count'])

key  num1 count  num2
0   c     2   two     1
1   e     5   two     2

In [18]:
pd.merge(df1, df2, 
         on='key', 
         suffixes=('_df1', '_df2'))

key  num1 count_df1  num2 count_df2
0   b     1     three     0       one
1   c     2       two     1       two
2   c     3       one     1       two
3   e     5       two     2       two

In [19]:
pd.merge(df1, df2, 
         on='key')

key  num1 count_x  num2 count_y
0   b     1   three     0     one
1   c     2     two     1     two
2   c     3     one     1     two
3   e     5     two     2     two

## Merging on index

In [29]:
df1=pd.DataFrame(
    {"letter":["a","a","b",
               "b","a","c"],
     "num":range(6)}) 
df2=pd.DataFrame(
    {"value":[3,5,7]},
    index=["a","b","e"])

In [30]:
df1.head()

letter  num
0      a    0
1      a    1
2      b    2
3      b    3
4      a    4

In [31]:
df2.head()

value
a      3
b      5
e      7

In [36]:
pd.merge(df1,df2,
         left_on='letter',right_index=True).reset_index(drop = True)

letter  num  value
0      a    0      3
1      a    1      3
2      a    4      3
3      b    2      5
4      b    3      5

In [37]:
right=pd.DataFrame(
    [[1,2],[3,4],[5,6]],
    index=["a","c","d"],
    columns=["Tom","Tim"])


left=pd.DataFrame(
    [[7,8],[9,10],[11,12],[13,14]],
    index=["a","b","e","f"],
    columns=["Sam","Kim"])

In [38]:
right.head()

Tom  Tim
a    1    2
c    3    4
d    5    6

In [39]:
left.head()

Sam  Kim
a    7    8
b    9   10
e   11   12
f   13   14

In [40]:
pd.merge(right,left, 
         right_index=True, 
         left_index=True, 
         how="inner")

# inner/outer/left/right

Tom  Tim  Sam  Kim
a    1    2    7    8

In [ ]:
# 2 columns
# 2 indexes
# column and index

## Concatenating Along an Axis

In [43]:
seq= np.arange(20).reshape((4, 5))
seq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
np.concatenate([seq,seq], axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [45]:
np.concatenate([seq, seq], axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
data1 = pd.Series(
    [0, 1], index=['a', 'b'])

data2 = pd.Series(
    [2,3,4], index=['c','d','e'])

data3 = pd.Series(
    [5, 6], index=['f', 'g'])

In [47]:
pd.concat([data1,data2,data3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [48]:
pd.concat([data1, data2, data3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [49]:
data4= pd.Series([10,11,12], 
                 index=['a','b',"c"])



In [50]:
data1.head()

a    0
b    1
dtype: int64

In [51]:
data4.head()

a    10
b    11
c    12
dtype: int64

In [52]:
pd.concat([data1,data4],axis=1,join="inner")

0   1
a  0  10
b  1  11

In [53]:
pd.concat([data1,data4],axis=0,join="inner")

a     0
b     1
a    10
b    11
c    12
dtype: int64

In [ ]:
# joining dataframes : merge
# append : concat